const data =[
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹403.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-10%",
      name: "Mamaearth Vitamin C Daily Glow Sunscreen SPF 50 PA+++ ",
      category: "women",
      new_price: "₹449.00",
      "canAddToCart": false,
      id: 3004,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.8,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/311UQSlLlDL.jpg",
      "asin": "B0CT88LY2L",
      "productLink": "/dp/B0CT88LY2L/ref=va_live_carousel",
      "brand": "Mamaearth",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹379.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-5%",
      name: "Minimalist Sunscreen SPF 50 PA++++ | Clinically Tested in US (In-Vivo) ",
      category: "women",
      new_price: "₹399.00",
      "canAddToCart": false,
      id: 17839,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/313nf+p926L.jpg",
      "asin": "B09FPS9D5T",
      "productLink": "/dp/B09FPS9D5T/ref=va_live_carousel",
      "brand": "Minimalist",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "5% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹322.00",
     
      
      "formattedSellerDiscountPercentage": "-32%",
      name: "The Moms Co. Natural Vita Rich Under Eye Cream for Dark Circles for Women & Men enriched with Chia Seed Oil",
      category: "women",
      new_price: "₹474.00",
      "canAddToCart": false,
      id: 21799,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 3,
      "digitalProduct": false,
      "ratingValue": 3.7,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41lUwO3PGoL.jpg",
      "asin": "B07JF5761L",
      "productLink": "/dp/B07JF5761L/ref=va_live_carousel",
      "brand": "The Moms Co",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹419.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-16%",
      name: "Dermafique Advanced Repair Night Cream with Niacinamide – 30g",
      category: "women",
      new_price: "₹499.00",
      "canAddToCart": false,
      id: 28,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31YSu5MFn8L.jpg",
      "asin": "B0BXX6WFC7",
      "productLink": "/dp/B0BXX6WFC7/ref=va_live_carousel",
      "brand": "Dermafique",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹440.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-55%",
      name: "Dermafique Sun Defense All Matte, SPF 50, PA +++ Sunscreen 30g",
      category: "women",
      new_price: "₹979.00",
      "canAddToCart": false,
      id: 705,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31A0Qy8jIeL.jpg",
      "asin": "B081BGNTDT",
      "productLink": "/dp/B081BGNTDT/ref=va_live_carousel",
      "brand": "Dermafique",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹402.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-55%",
      name: "Brillare 10% Vitamin C Serum, Bright & Glowing Skin with Probiotics",
      category: "women",
      new_price: "₹895.00",
      "canAddToCart": false,
      id: 462,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41IEABQ3pfL.jpg",
      "asin": "B0BBMGVZKC",
      "productLink": "/dp/B0BBMGVZKC/ref=va_live_carousel",
      "brand": "BRILLARE",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹450.00",
        
      
      
      name: "Forest Essentials Facial Tonic Mist with Pure Rosewater ",
      category: "women",
      new_price: null,
      "canAddToCart": false,
      id: 97,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31P2d0UeiDL.jpg",
      "asin": "B09ZVGH8MG",
      "productLink": "/dp/B09ZVGH8MG/ref=va_live_carousel",
      "brand": "Forest Essentials",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹429.00",
     
      
               
      name: "The Face Shop Non-Sticky Transparent 3 in 1 Aloe Fresh Soothing gel for Skin",
      category: "men",
      new_price: "₹490.00",
      "canAddToCart": false,
      id: 4191,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.5,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41pERpwT28L.jpg",
      "asin": "B01L2CI2DQ",
      "productLink": "/dp/B01L2CI2DQ/ref=va_live_carousel",
      "brand": "The Face Shop",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "12% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹394.00",
      "hasHalfStar": false,
      
               
      name: "Aqualogica Men & Women Radiance+ Dewy Sunscreen For All Skin Types",
      category: "men",
      new_price: "₹449.00",
      "canAddToCart": false,
      id: 6221,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41XmorlLnBL.jpg",
      "asin": "B0B3MNVPDV",
      "productLink": "/dp/B0B3MNVPDV/ref=va_live_carousel",
      "brand": "Aqualogica",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹350.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-10%",
      name: "Deconstruct 1% Squalane Moisturizer with 0.2% Hyaluronic acid ",
      category: "women",
      new_price: "₹389.00",
      "canAddToCart": false,
      id: 16,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31mCLYJ5vkL.jpg",
      "asin": "B0BZSTYQ4V",
      "productLink": "/dp/B0BZSTYQ4V/ref=va_live_carousel",
      "brand": "Deconstruct",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "10% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹395.00",
      "hasHalfStar": false,
      
      
      name: "Brillare Professional Skin Brightening/Lightening Face Wash",
      category: "women",
      new_price: null,
      "canAddToCart": false,
      id: 464,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/318nfl+7u+L.jpg",
      "asin": "B0132H7D66",
      "productLink": "/dp/B0132H7D66/ref=va_live_carousel",
      "brand": "BRILLARE",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹420.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-15%",
      name: "Dot & Key Vitamin C + E Super Bright Under Eye Cream ",
      category: "men",
      new_price: "₹495.00",
      "canAddToCart": false,
      id: 97,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41cCjnm63UL.jpg",
      "asin": "B0C2Z9YF51",
      "productLink": "/dp/B0C2Z9YF51/ref=va_live_carousel",
      "brand": "DOT & KEY",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "15% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹489.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-1%",
      name: "La Pink Strawberry Natural Tinted Lip Balm with Shea & Kokum Butter ",
      category: "women",
      new_price: "₹495.00",
      "canAddToCart": false,
      id: 0,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 0,
      "digitalProduct": false,
      "ratingValue": 0,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41RGaxr3vdL.jpg",
      "asin": "B0CR7CC7XF",
      "productLink": "/dp/B0CR7CC7XF/ref=va_live_carousel",
      "brand": "La Pink",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹351.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-11%",
      name: "Dot & Key Ceramides Moisturizer with Hyaluronic for Intense Moisturizing ",
      category: "women",
      new_price: "₹395.00",
      "canAddToCart": false,
      id: 3775,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31ozJnM-98L.jpg",
      "asin": "B0BDVG99J5",
      "productLink": "/dp/B0BDVG99J5/ref=va_live_carousel",
      "brand": "DOT & KEY",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "11% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹268.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-10%",
      name: "The Derma Co 2% Niacinamide Gentle Skin Cleanser for Sensitive, Dry",
      category: "men",
      new_price: "₹299.00",
      "canAddToCart": false,
      id: 417,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31whfHxs1HL.jpg",
      "asin": "B0CD1RRT75",
      "productLink": "/dp/B0CD1RRT75/ref=va_live_carousel",
      "brand": "The Derma Co",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹375.00",
     
      
      "formattedSellerDiscountPercentage": "-6%",
      name: "Cetaphil Face Wash Gentle Skin Cleanser for Dry to Normal",
      category: "women",
      new_price: "₹399.00",
      "canAddToCart": false,
      id: 18343,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31K5tBuI3ZL.jpg",
      "asin": "B01CCGW4OE",
      "productLink": "/dp/B01CCGW4OE/ref=va_live_carousel",
      "brand": "Cetaphil",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹379.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-5%",
      name: "Minimalist Pha 3% Alcohol Free Face Toner, 150 Ml | Pore Tightening ",
      category: "women",
      new_price: "₹399.00",
      "canAddToCart": false,
      id: 6602,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41lkPzEAn5L.jpg",
      "asin": "B08S581RXJ",
      "productLink": "/dp/B08S581RXJ/ref=va_live_carousel",
      "brand": "Minimalist",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "5% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹495.00",
      "hasHalfStar": false,
      
      
      name: "Brillare Rose Face Wash, Anti Ageing Skin, Sandalwood & Coconut Face Wash ",
      category: "men",
      new_price: null,
      "canAddToCart": false,
      id: 1104,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/51ctkCq-KqL.jpg",
      "asin": "B0BV76CY7D",
      "productLink": "/dp/B0BV76CY7D/ref=va_live_carousel",
      "brand": "BRILLARE",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹396.00",
     
      
      "formattedSellerDiscountPercentage": "-11%",
      name: "DOT & KEY Vitamin C + E Super Bright Sunscreen Spf ",
      category: "women",
      new_price: "₹445.00",
      "canAddToCart": false,
      id: 3052,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31kx4kicRyL.jpg",
      "asin": "B0BLK4YRSN",
      "productLink": "/dp/B0BLK4YRSN/ref=va_live_carousel",
      "brand": "DOT & KEY",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "11% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹306.00",
      "hasHalfStar": false,
      
               
      name: "Mamaearth Rice Face Scrub for Glowing Skin, With Rice Water",
      category: "women",
      new_price: "₹349.00",
      "canAddToCart": false,
      id: 492,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31e+BdPHw5L.jpg",
      "asin": "B09Z63S7XR",
      "productLink": "/dp/B09Z63S7XR/ref=va_live_carousel",
      "brand": "Mamaearth",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "12% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹323.00",
     
      
      "formattedSellerDiscountPercentage": "-35%",
      name: "The Man Company Lip Care Combo with Lip Scrub ",
      category: "men",
      new_price: "₹498.00",
      "canAddToCart": false,
      id: 622,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 3,
      "digitalProduct": false,
      "ratingValue": 3.7,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41qgsE3kCqL.jpg",
      "asin": "B09812KY1R",
      "productLink": "/dp/B09812KY1R/ref=va_live_carousel",
      "brand": "The Man Company",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹284.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-5%",
      name: "Minimalist Gentle Face Wash With 6% Oat Extract ",
      category: "women",
      new_price: "₹299.00",
      "canAddToCart": false,
      id: 1672,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41pPQww69WL.jpg",
      "asin": "B09VPN4NTM",
      "productLink": "/dp/B09VPN4NTM/ref=va_live_carousel",
      "brand": "Minimalist",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "5% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹476.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-20%",
      name: "Foxtale 15% Vitamin C Face Serum for Glowing Skin",
      category: "men",
      new_price: "₹595.00",
      "canAddToCart": false,
      id: 2164,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/41rpYGP-GXL.jpg",
      "asin": "B09RZPZCHS",
      "productLink": "/dp/B09RZPZCHS/ref=va_live_carousel",
      "brand": "FoxTale",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "20% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹387.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-14%",
      name: "Dot & Key 10% Niacinamide + Cica Serum | Reduces Acne & Dark Spots ",
      category: "kid",
      new_price: "₹450.00",
      "canAddToCart": false,
      id: 328,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31dURf6mJqL.jpg",
      "asin": "B0BJ77CVGY",
      "productLink": "/dp/B0BJ77CVGY/ref=va_live_carousel",
      "brand": "DOT & KEY",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "14% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹335.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-15%",
      name: "Dot & Key Rice Water Hydrating Toner With Hyaluronic ",
      category: "women",
      new_price: "₹395.00",
      "canAddToCart": false,
      id: 381,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31duInhjBhL.jpg",
      "asin": "B09RWQ54C5",
      "productLink": "/dp/B09RWQ54C5/ref=va_live_carousel",
      "brand": "DOT & KEY",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "15% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹395.00",
      "hasHalfStar": false,
      
      
      name: "RE' EQUIL Oxybenzone and OMC Free Sunscreen For Oily",
      category: "kid",
      new_price: null,
      "canAddToCart": false,
      id: 8225,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/2134rIz8wxL.jpg",
      "asin": "B07GKXDP8P",
      "productLink": "/dp/B07GKXDP8P/ref=va_live_carousel",
      "brand": "RE' EQUIL",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹306.00",
      "hasHalfStar": false,
      
               
      name: "Mamaearth Charcoal Face Scrub for Oily ",
      category: "kid",
      new_price: "₹349.00",
      "canAddToCart": false,
      id: 3379,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/416NWXfnueL.jpg",
      "asin": "B085NYMG6Z",
      "productLink": "/dp/B085NYMG6Z/ref=va_live_carousel",
      "brand": "Mamaearth",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "12% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹299.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-63%",
      name: "Cerulean Moisturiser for Dry Skin 100gm Instant Hydration ",
      category: "women",
      new_price: "₹799.00",
      "canAddToCart": false,
      id: 51,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/416DiIyV52L.jpg",
      "asin": "B0BHZ6HRQ7",
      "productLink": "/dp/B0BHZ6HRQ7/ref=va_live_carousel",
      "brand": "Cerulean",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: null,
      "hasHalfStar": false,
      
      
      name: "Kama Ayurveda Pure Rose, Pack of 50ml liquid",
      category: "kid",
      new_price: null,
      "canAddToCart": false,
      id: 5860,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/312OPT6eQKL.jpg",
      "asin": "B01BGJ07GK",
      "productLink": "/dp/B01BGJ07GK/ref=va_live_carousel",
      "brand": "Kama Ayurveda",
      "dealBadge": null,
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹284.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-5%",
      name: "Minimalist 2% Salicylic Acid Face Wash For Oily Skin | Sulphate free",
      category: "women",
      new_price: "₹299.00",
      "canAddToCart": false,
      id: 13234,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31fIPTLyP0L.jpg",
      "asin": "B096PJMGPL",
      "productLink": "/dp/B096PJMGPL/ref=va_live_carousel",
      "brand": "Minimalist",
      "dealBadge": {
        "messageText": "Limited time deal",
        "messageBackgroundColor": "ffffff",
        "messageTimerEndTime": null,
        "labelBackgroundColor": "CC0C39",
        "labelText": "5% off",
        "messageColor": "CC0C39",
        "labelColor": "ffffff"
      },
      "offerListingId": null
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹386.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-8%",
      name: "Plum 3% Niacinamide & Rice Water Face Toner | With Rice Ferment Extract ",
      category: "kid",
      new_price: "₹420.00",
      "canAddToCart": false,
      id: 1334,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31M2OhN9HBL.jpg",
      
    },
    {
      "singularItem": false,
      "promotionType": null,
      old_price: "₹313.00",
      "hasHalfStar": false,
      
      "formattedSellerDiscountPercentage": "-10%",
      name: "The Derma Co 10% Vitamin C Face Serum with Vitamin C",
      category: "kid",
      new_price: "₹349.00",
      "canAddToCart": false,
      id: 8536,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      image: "https://images-na.ssl-images-amazon.com/images/I/31+dCaycMIL.jpg",
      
      },
      
    
  ]
export default data;
